import Head from 'next/head'
import { Inter } from '@next/font/google'
import { SiNike } from 'react-icons/si'
import { BsBag } from 'react-icons/bs'
import { MdArrowBackIosNew } from 'react-icons/md'
import { MdArrowForwardIos } from 'react-icons/md'
import Item from '@/components/item'
import { useSpring, animated, config } from 'react-spring';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // Navbar Animation
  const logoAnimation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 10
  })
  const navAnimation1 = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 200
  })
  const navAnimation2 = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 250
  })
  const navAnimation3 = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 300
  })
  const shopIconAnimation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 550
  })

  // Hero Animation
  const heroh2Animation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 1300
  })
  const heroh1Animation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 1500
  })
  const heropAnimation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 1700
  })
  const herobuttonAnimation1 = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 1900
  })
  const herobuttonAnimation2 = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 2000
  })
  const heroImageAnimation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 2100
  })
  // Trending Animation
  const heroTrendAnimation = useSpring({
    from: { opacity: 0, transform: 'translateY(130px)' },
    to: { opacity: 1, transform: 'translateY(0)' },
    delay: 3000
  })

  return (
    <>
      <Head>
        <title>Nike</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Navar */}
      <nav className='flex justify-between m-5 items-center'>
        <div className='mask'>
          <animated.div style={logoAnimation}>
            <SiNike size={45} className='cursor-pointer'/>
          </animated.div>
        </div>
        <div className='flex gap-5'>
          <div className='mask'>
            <animated.h1 style={navAnimation1} className='cursor-pointer hover:underline'>Men</animated.h1>
          </div>
          <div className='mask'>
            <animated.h1 style={navAnimation2} className='cursor-pointer hover:underline'>Women</animated.h1>
          </div>
          <div className='mask'>
            <animated.h1 style={navAnimation3} className='cursor-pointer hover:underline'>Kids</animated.h1>
          </div>
        </div>
        <div className='mask'>
          <animated.div style={shopIconAnimation}>
            <BsBag size={20} className='cursor-pointer'/>
          </animated.div>
        </div>
      </nav>
      {/* Hero */}
      <div className='flex-col justify-center py-[100px] text-[#111111]'>
        <div className='mask'>
          <animated.h2 style={heroh2Animation} className='text-center'>Just In: Nike Invincible 3</animated.h2>
        </div>
        <div className='mask'>
          <animated.h1 style={heroh1Animation} className='text-center font-bold text-6xl'>FEEL IT TO BELIEVE IT</animated.h1>
        </div>
        <div className='mask'>
          <animated.p style={heropAnimation} className='text-center my-6'>Our most cushioned road-running shoe gives you extraordinary comfort,<br/>supreme softness and lightweight support through every mile.</animated.p>
        </div>
          <div className='text-center mask'>
            <animated.button style={herobuttonAnimation1} className='bg-[#111111] p-2 px-5 mx-2 text-white rounded-full transition-all hover:scale-110'>Shop Men's</animated.button>
            <animated.button style={herobuttonAnimation2} className='bg-[#111111] p-2 px-5 mx-2 text-white rounded-full transition-all hover:scale-110'>Shop Women's</animated.button>
          </div>
      </div>
      <div className='flex justify-center items-center'>
        <animated.img style={heroImageAnimation} className=' rounded-3xl' src="https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" alt="hero image"/>
      </div>
      {/* Featured Items */}
      <animated.div style={heroTrendAnimation} >
        <div className='mx-10 my-6 flex justify-between items-center'>
          <h1 className='text-xl font-medium'>Trending This Week</h1>
          <div className='flex'>
            <MdArrowBackIosNew size={45} className='bg-[#E5E5E5] rounded-full p-4 m-2'/>
            <MdArrowForwardIos size={45} className='bg-[#E5E5E5] rounded-full p-4 m-2'/>
          </div>
        </div>
        <div style={{ height: '500px', overflow: 'auto' }}>
  <div className='flex gap-10 mx-10 my-6'>
    <Item 
      image='https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/w_300,c_limit/86f31dde-06ea-42dc-8516-64614e3ee408/jordan-6-rings-older-shoes-K41p0C.png'
      title='Jordan 6 Rings'
      price='R 2 299,95'
      category='Older Kids Shoes'
    />
    <Item 
      image='https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/w_300,c_limit/a42a5d53-2f99-4e78-a081-9d07a2d0774a/air-force-1-07-shoe-ZLZpmn.png'
      title="Nike Air Force 1 '07"
      price='R 2 299,95'
      category="Men's Shoe"
    />
    <Item 
      image='https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/h_602,c_limit/3cdbf180-ae3f-4549-a458-40d2476671a1/air-jordan-3-retro-se-older-shoes-CSgC3L.png'
      title="Air jordan 3 Retro SE"
      price='R 2 799,95'
      category="Older Kids Shoes"
    />
    <Item 
      image='https://static.nike.com/a/images/q_auto:eco/t_product_v1/f_auto/dpr_1.0/h_308,c_limit/c6d9d042-f0b9-46a3-bd1f-04e16541a1d9/air-force-1-07-next-nature-shoes-lkVhs6.png'
      title="Nike Air Force 1 '07"
      price='R 2 299,95'
      category="Wome's shoes"
    />
  </div>
</div>

      </animated.div>
    </>
  )
}
